apiVersion: v1
data:
  INFLUXDB_DATABASE: dGVuaXRlcmRi
  INFLUXDB_HOST: aW5mbHV4ZGI=
  INFLUXDB_PASSWORD: YWRtaW4=
  INFLUXDB_USERNAME: YWRtaW4=
kind: Secret
metadata:
  creationTimestamp: null
  name: influxdb-secrets
